---
authenticationBasicEnabled: true
authenticationBasicProfileName: ""
authenticationBasicRadiusDomain: ""
authenticationBasicType: none
authenticationClientCertAllowApiProvidedUsernameEnabled: false
authenticationClientCertEnabled: false
authenticationClientCertMaxChainDepth: 3
authenticationClientCertRevocationCheckMode: allow-valid
authenticationClientCertUsernameSource: common-name
authenticationClientCertValidateDateEnabled: true
authenticationKerberosAllowApiProvidedUsernameEnabled: false
authenticationKerberosEnabled: false
authorizationLdapGroupMembershipAttributeName: memberOf
authorizationProfileName: ""
authorizationType: internal
bridgingTlsServerCertEnforceTrustedCommonNameEnabled: true
bridgingTlsServerCertMaxChainDepth: 3
bridgingTlsServerCertValidateDateEnabled: true
counter:
  controlRxByteCount: 632
  controlRxMsgCount: 8
  controlTxByteCount: 295
  controlTxMsgCount: 2
  dataRxByteCount: 0
  dataRxMsgCount: 0
  dataTxByteCount: 0
  dataTxMsgCount: 0
  discardedRxMsgCount: 0
  discardedTxMsgCount: 0
  loginRxMsgCount: 2
  loginTxMsgCount: 2
  msgSpoolRxMsgCount: 0
  msgSpoolTxMsgCount: 0
  tlsRxByteCount: 0
  tlsTxByteCount: 0
distributedCacheManagementEnabled: true
dmrEnabled: true
enabled: true
eventConnectionCountThreshold:
  clearPercent: 60
  setPercent: 80
eventEgressFlowCountThreshold:
  clearPercent: 60
  setPercent: 80
eventEgressMsgRateThreshold:
  clearValue: 3000000
  setValue: 4000000
eventEndpointCountThreshold:
  clearPercent: 60
  setPercent: 80
eventIngressFlowCountThreshold:
  clearPercent: 60
  setPercent: 80
eventIngressMsgRateThreshold:
  clearValue: 3000000
  setValue: 4000000
eventLargeMsgThreshold: 1024
eventLogTag: ""
eventMsgSpoolUsageThreshold:
  clearPercent: 60
  setPercent: 80
eventPublishClientEnabled: false
eventPublishMsgVpnEnabled: false
eventPublishSubscriptionMode: "off"
eventPublishTopicFormatMqttEnabled: false
eventPublishTopicFormatSmfEnabled: true
eventServiceAmqpConnectionCountThreshold:
  clearPercent: 60
  setPercent: 80
eventServiceMqttConnectionCountThreshold:
  clearPercent: 60
  setPercent: 80
eventServiceRestIncomingConnectionCountThreshold:
  clearPercent: 60
  setPercent: 80
eventServiceSmfConnectionCountThreshold:
  clearPercent: 60
  setPercent: 80
eventServiceWebConnectionCountThreshold:
  clearPercent: 60
  setPercent: 80
eventSubscriptionCountThreshold:
  clearPercent: 60
  setPercent: 80
eventTransactedSessionCountThreshold:
  clearPercent: 60
  setPercent: 80
eventTransactionCountThreshold:
  clearPercent: 60
  setPercent: 80
exportSubscriptionsEnabled: false
jndiEnabled: true
maxConnectionCount: 100
maxEffectiveEndpointCount: 100
maxEffectiveRxFlowCount: 100
maxEffectiveSubscriptionCount: 50000
maxEffectiveTransactedSessionCount: 100
maxEffectiveTransactionCount: 500
maxEffectiveTxFlowCount: 100
maxEgressFlowCount: 1000
maxEndpointCount: 1000
maxIngressFlowCount: 1000
maxMsgSpoolUsage: 1500
maxSubscriptionCount: 500000
maxTransactedSessionCount: 1000
maxTransactionCount: 5000
mqttRetainMaxMemory: -1
msgReplayActiveCount: 0
msgReplayFailedCount: 0
msgReplayInitializingCount: 0
msgReplayPendingCompleteCount: 0
msgSpoolUsage: 0
msgVpnName: default
rate:
  averageRxByteRate: 0
  averageRxMsgRate: 0
  averageTxByteRate: 0
  averageTxMsgRate: 0
  rxByteRate: 0
  rxMsgRate: 0
  tlsAverageRxByteRate: 0
  tlsAverageTxByteRate: 0
  tlsRxByteRate: 0
  tlsTxByteRate: 0
  txByteRate: 0
  txMsgRate: 0
restTlsServerCertEnforceTrustedCommonNameEnabled: true
restTlsServerCertMaxChainDepth: 3
restTlsServerCertValidateDateEnabled: true
sempOverMsgBusAdminClientEnabled: true
sempOverMsgBusAdminDistributedCacheEnabled: true
sempOverMsgBusAdminEnabled: true
sempOverMsgBusEnabled: true
sempOverMsgBusShowEnabled: true
serviceAmqpMaxConnectionCount: 100
serviceAmqpPlainTextEnabled: true
serviceAmqpPlainTextListenPort: 5672
serviceAmqpPlainTextUp: true
serviceAmqpTlsEnabled: true
serviceAmqpTlsFailureReason: No Cert
serviceAmqpTlsListenPort: 5671
serviceAmqpTlsUp: false
serviceMqttMaxConnectionCount: 100
serviceMqttPlainTextEnabled: true
serviceMqttPlainTextListenPort: 1883
serviceMqttPlainTextUp: true
serviceMqttTlsEnabled: true
serviceMqttTlsFailureReason: No Cert
serviceMqttTlsListenPort: 8883
serviceMqttTlsUp: false
serviceMqttTlsWebSocketEnabled: true
serviceMqttTlsWebSocketFailureReason: No Cert
serviceMqttTlsWebSocketListenPort: 8443
serviceMqttTlsWebSocketUp: false
serviceMqttWebSocketEnabled: true
serviceMqttWebSocketListenPort: 8000
serviceMqttWebSocketUp: true
serviceRestIncomingMaxConnectionCount: 100
serviceRestIncomingPlainTextEnabled: true
serviceRestIncomingPlainTextListenPort: 9000
serviceRestIncomingPlainTextUp: true
serviceRestIncomingTlsEnabled: true
serviceRestIncomingTlsFailureReason: No Cert
serviceRestIncomingTlsListenPort: 9443
serviceRestIncomingTlsUp: false
serviceRestMode: messaging
serviceRestOutgoingMaxConnectionCount: 100
serviceSmfMaxConnectionCount: 100
serviceSmfPlainTextEnabled: true
serviceSmfPlainTextUp: true
serviceSmfTlsEnabled: true
serviceSmfTlsFailureReason: No Cert
serviceSmfTlsUp: false
serviceWebMaxConnectionCount: 100
serviceWebPlainTextEnabled: true
serviceWebPlainTextUp: true
serviceWebTlsEnabled: true
serviceWebTlsFailureReason: No Cert
serviceWebTlsUp: false
state: up
subscriptionExportProgress: 100
systemManager: false
tlsAllowDowngradeToPlainTextEnabled: false